In [2]:
import pandas as pd
from datasets import load_dataset
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()
df['job_posted_date']= pd.to_datetime(df.job_posted_date)
import matplotlib.pyplot as plt

In [3]:
df[pd.notna(df['salary_year_avg'])]['salary_year_avg']

28        109500.0
77        140000.0
92        120000.0
100       228222.0
109        89000.0
            ...
785624    139216.0
785641    150000.0
785648    221875.0
785682    157500.0
785692    157500.0
Name: salary_year_avg, Length: 22003, dtype: float64

In [4]:
df_salary = df[pd.notna(df['salary_year_avg'])].copy()

def projected_salary (salary):
    return salary * 1.03

df_salary['salary_year_infilated'] = df_salary['salary_year_avg'].apply(projected_salary)

df_salary[['salary_year_avg','salary_year_infilated' ]]

        salary_year_avg  salary_year_infilated
28             109500.0              112785.00
77             140000.0              144200.00
92             120000.0              123600.00
100            228222.0              235068.66
109             89000.0               91670.00
...                 ...                    ...
785624         139216.0              143392.48
785641         150000.0              154500.00
785648         221875.0              228531.25
785682         157500.0              162225.00
785692         157500.0              162225.00

[22003 rows x 2 columns]

In [5]:
df_salary['salary_year_infilated'] = df_salary['salary_year_avg'].apply(lambda salary:salary * 1.03)

df_salary[['salary_year_avg','salary_year_infilated' ]]

        salary_year_avg  salary_year_infilated
28             109500.0              112785.00
77             140000.0              144200.00
92             120000.0              123600.00
100            228222.0              235068.66
109             89000.0               91670.00
...                 ...                    ...
785624         139216.0              143392.48
785641         150000.0              154500.00
785648         221875.0              228531.25
785682         157500.0              162225.00
785692         157500.0              162225.00

[22003 rows x 2 columns]

In [6]:
df['job_skills'].head(10)

0                                                  NaN
1    ['r', 'python', 'sql', 'nosql', 'power bi', 't...
2    ['python', 'sql', 'c#', 'azure', 'airflow', 'd...
3    ['python', 'c++', 'java', 'matlab', 'aws', 'te...
4    ['bash', 'python', 'oracle', 'aws', 'ansible',...
5                             ['python', 'sql', 'gcp']
6    ['sql', 'python', 'java', 'sql server', 'gcp',...
7    ['sql', 'nosql', 'gcp', 'azure', 'aws', 'bigqu...
8                  ['excel', 'powerpoint', 'power bi']
9    ['sql', 'python', 'r', 'mongodb', 'mongodb', '...
Name: job_skills, dtype: str

In [7]:
import ast

df['job_skills'] = df['job_skills'].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else []
)

In [8]:
df['job_skills']

0                                                        []
1                [r, python, sql, nosql, power bi, tableau]
2         [python, sql, c#, azure, airflow, dax, docker,...
3         [python, c++, java, matlab, aws, tensorflow, k...
4         [bash, python, oracle, aws, ansible, puppet, j...
                                ...
785736    [bash, python, perl, linux, unix, kubernetes, ...
785737                               [sas, sas, sql, excel]
785738                                  [powerpoint, excel]
785739    [python, go, nosql, sql, mongo, shell, mysql, ...
785740                                          [aws, flow]
Name: job_skills, Length: 785741, dtype: object

In [9]:
def clean_list(skill_list):
    if pd.notna(skill_list):
        return ast.literal_eval(skill_list)

    df['job_skills'] = df['job_skills'].apply(clean_list)

In [10]:
type (df['job_skills'][0])

list

In [16]:
df_salary.columns

Index(['job_title_short', 'job_title', 'job_location', 'job_via',
       'job_schedule_type', 'job_work_from_home', 'search_location',
       'job_posted_date', 'job_no_degree_mention', 'job_health_insurance',
       'job_country', 'salary_rate', 'salary_year_avg', 'salary_hour_avg',
       'company_name', 'job_skills', 'job_type_skills',
       'salary_year_infilated'],
      dtype='str')

In [21]:
def projected_salary(row):
    if 'senior' in row ['job_title_short']:
        return 1.05* row ['salary_year_avg']
    else:
        return 1.03* row ['salary_year_avg']

df_salary['salary_year_infilated'] = df_salary.apply(projected_salary,  axis =1 )

df_salary[['job_title_short', 'salary_year_avg', 'salary_year_infilated']]

       job_title_short  salary_year_avg  salary_year_infilated
28      Data Scientist         109500.0              112785.00
77       Data Engineer         140000.0              144200.00
92       Data Engineer         120000.0              123600.00
100     Data Scientist         228222.0              235068.66
109       Data Analyst          89000.0               91670.00
...                ...              ...                    ...
785624   Data Engineer         139216.0              143392.48
785641   Data Engineer         150000.0              154500.00
785648  Data Scientist         221875.0              228531.25
785682  Data Scientist         157500.0              162225.00
785692  Data Scientist         157500.0              162225.00

[22003 rows x 3 columns]

SyntaxError: unmatched '}' (70646322.py, line 1)

In [23]:
00

0